version: '3'

services:
  dev:
    build: .
    image: jobs4good:${DOCKER_TAG:-latest}
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - bundler-cache:/usr/local/bundle
    working_dir: /usr/src/app
    command: bundle exec rails s

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=dbsecret
      - POSTGRES_USER=dbuser
      - POSTGRES_DB=jobs4good
    networks:
      default:
        aliases:
          - postgres.local

volumes:
  bundler-cache:

networks:
  default:
