version: '3'

services:
  dev:
    depends_on:
      - postgres
    image: ruby:2.3.3
    volumes:
      - .:/usr/src/app
      - bundler-cache:/usr/local/bundle/cache
    working_dir: /usr/src/app
    command: bash

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=dbsecret
      - POSTGRES_USER=dbuser
      - POSTGRES_DB=jobs4good
    networks:
      default:
        aliases:
          - postgres.local

volumes:
  bundler-cache:

networks:
  default:
